### PR TITLE
[src] Add targets argument to musdb18_dataset.py

### PR DESCRIPTION
**Pull request by mpariente**
The is to address the "issue" mentioned in #47.
We can add a `targets` argument to the dataset so that the return sources are in the form of a Tensor (with the required target sources stacked in the given order) instead of the dict.

```python
# Mix all sources and return a dict
MUSDB18Dataset(root)
# Mix only 'vocals', 'bass', 'drums' and return dict
MUSDB18Dataset(root, sources=['vocals', 'bass', 'drums'])
# Mix only 'vocals', 'bass', 'drums' and return stacked vocals and drums (sorry bass)
MUSDB18Dataset(root, sources=['vocals', 'bass', 'drums'], targets=['vocals', 'drums'])
```
The main use case is that we don't have to subclass `System` to use it, which makes sense!

@faroit Could you review please and tell me if you'd be fine with that
@groadabike, would this suit your needs?

### CODE REVIEW

**Comment by faroit** [comment]
Yes a list of target can make sense but I don't understand why this would need to be a stacked tensor instead of a dict. Couldn't users do the stacking inside their model or loss?

**Comment by mpariente** [comment]
> Yes a list of target can make sense but I don't understand why this would need to be a stacked tensor instead of a dict. Couldn't users do the stacking inside their model or loss?

They could. But then it's almost the same as not having the targets argument.
If you use ConvTasNet with a L1 loss (for example) and MUSDB18 with targets arg, you would be able to use the default `System` ([see here](https://github.com/mpariente/asteroid/blob/master/asteroid/engine/system.py#L79) for the forward that would use the stacked tensors in the loss).

It's just a matter of ease-of-use IMO.

**Comment by faroit** [comment]
> It's just a matter of ease-of-use IMO.

yes, ok. I agree then

**Comment by mpariente** [comment]
Cool thanks !

**Pull request merged**
