### PR TITLE
Fix black 20.8b1 update

### PR DESCRIPTION
**Pull request by jonashaag**
#265 was formatted with black 19 🤦

### CODE REVIEW

**Comment by mpariente** [comment]
Are you sure it's not a matter of line length only now?

**Comment by jonashaag** [comment]
I don't know what changed with black 20, but this is what I get when I update pre-commit to black20 and re-run it on all files

**Comment by mpariente** [comment]
What is the command you issued to run it on all files please? 
If I update and run it, don't have the same output..

**Comment by jonashaag** [comment]
`pre-commit run -a`

(note it also changes some whitespace in `.md` files which I ignored)

**Comment by mpariente** [comment]
```bash
(asteroid) @asteroid$ python -m black --config=pyproject.toml --check asteroid tests
would reformat /home/mparient/PhD_Main/AsSteroid/asteroid/utils/hub_utils.py
would reformat /home/mparient/PhD_Main/AsSteroid/asteroid/filterbanks/multiphase_gammatone_fb.py
would reformat /home/mparient/PhD_Main/AsSteroid/asteroid/data/avspeech_dataset.py
would reformat /home/mparient/PhD_Main/AsSteroid/asteroid/models/publisher.py
would reformat /home/mparient/PhD_Main/AsSteroid/asteroid/masknn/convolutional.py
Oh no! 💥 💔 💥
5 files would be reformatted, 83 files would be left unchanged.

```

**Comment by mpariente** [comment]
Ok, got it. I ran on the recipes as well, sorry. 
I'll add it to the CI.

**Comment by jonashaag** [comment]
Does `pre-commit run` also consider `pyproject.toml`?

**Comment by mpariente** [comment]
It's not clear to me, and it seems that it doesn't..

**Pull request merged**
