### PR TITLE
Split base model

### PR DESCRIPTION
**Pull request by jonashaag**
Part 2 of #224

### CODE REVIEW

**Comment by mpariente** [comment]
I know it was my idea but I think the name BaseEMDNet is not that clear. 
Do we plan that people will discover it easily because it's the baseclass of all the models we use for now? Otherwise, the name doesn't speak for itself.

**Comment by jonashaag** [comment]
Unfortunately I don't have a better naming suggestion. Maybe `BaseEncoderMaskerDecoderNet` is a bit better. But yes, I would expect people to find and understand the class pretty quickly despite its name.

**Comment by mpariente** [comment]
Maybe `BaseEncoderMaskerDecoder`? We don't really need the `Net`.

**Review by mpariente — APPROVED** [review]
Renamed to `BaseEncoderMaskerDecoder` instead, but otherwise it's perfect. 
Waiting for the CI to complete.

**Pull request merged**
