### PR TITLE
[src] Add sample_rate argument to all supported models.

### PR DESCRIPTION
**Pull request by mpariente**
Add samplerate argument to all models and pass it to the filterbank. This should work as is. 

Ref: #274 #283

### CODE REVIEW

**Comment by jonashaag** [comment]
What does this mean for pretrained models that we already have?

**Comment by mpariente** [comment]
For now, nothing. 
If there is no `sample_rate` in the pretrained model, we'll handle it in `from_pretrained`. But that'll be for a next PR.

**Comment by jonashaag** [comment]
Ok, LGTM, except for the denoising models which I’d say should have 16k (DCUNet and DCCRN)

**Comment by mpariente** [comment]
Changing it then.

**Pull request merged**
