### PR TITLE
Load models without sample_rate

### PR DESCRIPTION
**Pull request by mpariente**
This implements the loading of known models with known sample rate, and raises error when sample rate is not known. 

Also made a CLI to register sample rate to model (for the lazy ones). Is there a better name (more explicit) than `asteroid-cli register-samplerate`?

Refs: #274 #283 #284

### CODE REVIEW

**Comment by jonashaag** [comment]
This is great. LGTM!

**Comment by mpariente** [comment]
\rebase

**Comment by mpariente** [comment]
\rebase

**Comment by mpariente** [comment]
Missing test for the CLI. Merging anyway.

**Pull request merged**
