### PR TITLE
[docs] Brand new docs !

### PR DESCRIPTION
**Pull request by mpariente**
Here is a PR that aims at improving Asteroid's documentation. There are still lots of things to do and things I didn't find out how to do yet. 

- Couldn't use automodule on `asteroid.data` without members
- Couldn't have anchor point in the index when using automodule (I'd like to have all elements listed in the sidebar)
@mhu-coder @jonashaag Any idea how to do that? It would be great !

### Left to document
- Filterbanks more
- Losses more
- Models from scratch
- Utils
- Asteroid CLI
- Probably a tutorial on asteroid's complex number format
- Community stuff, how to contribute, troubleshooting etc.. 

Also, probably move consistency somewhere else??

### CODE REVIEW

**Comment by jonashaag** [comment]
>     * Couldn't use automodule on `asteroid.data` without members

What do you mean with that?

**Comment by mpariente** [comment]
I had to do that 
```rst
PyTorch Datasets
================

.. currentmodule:: asteroid.data

.. autoclass:: LibriMix
.. autoclass:: Wsj0mixDataset
.. autoclass:: WhamDataset
.. autoclass:: WhamRDataset
.. autoclass:: SmsWsjDataset
.. autoclass:: KinectWsjMixDataset
.. autoclass:: DNSDataset
.. autoclass:: MUSDB18Dataset
```

Instead, I'd like to do that 

```rst
PyTorch Datasets
================
.. automodule:: asteroid.data
   :members:
```

**Comment by mhu-coder** [comment]
Hey, sorry for the late reply.

I tried to generate the documentation and found that I was missing the sphinx extensions `m2r2`, `nbsphinx` used by `docs/source/conf.py`. Would it be sensible to add them to `requirements.txt`?

About the `autodoc` directive, have you tried with the `:imported-members:` added to `data.rst`? So the complete file would contain:

```rst
PyTorch Datasets
================

.. automodule:: asteroid.data
    :members:
    :imported-members:
```

Stupid question, is there a way to type double colon without github popping a floating window with all the available emojis (which makes the interface slow AF...)?

**Comment by mpariente** [comment]
Thanks for the answer. 
Yes, I can add the extensions to the docs requirements. 
I think I tried and didn't work either, I'll try again tomorrow !

About the `:`, if you add a space after it quite fast, it doesn't show up :joy: 
But I like emojis so I won't complain :star_struck:

**Comment by mpariente** [comment]
Correction, both extensions are in the `docs/requirements.txt` which is the one to build the docs.

**Comment by mhu-coder** [comment]
> I think I tried and didn't work either, I'll try again tomorrow !

Weird, it works on my end 😕 . When you try again, can you reload the page with `Ctrl + Shift + R`, which bypasses the cache? Otherwise, you may visualize an outdated html document.

> Correction, both extensions are in the docs/requirements.txt which is the one to build the docs.

Thanks for the clarification. I completely missed the file as I was expecting all the requirements to be in a single `requirements.txt` (habits 🙄...)

> Couldn't have anchor point in the index when using automodule (I'd like to have all elements listed in the sidebar)

Does this [stackoverflow](https://stackoverflow.com/questions/58486590/sphinx-sidebar-include-modules-functions-and-class-methods) thread describe what you want to achieve? Sounds like it's a work in progress in Sphinx 😖.

**Comment by mpariente** [comment]
Then, I'm happier with the current version that has the indices in the sidebar. 
Thanks for looking into it !

**Comment by mpariente** [comment]
Alright, I'm happy with the current version. It's not perfect but way better than before, let's merge it and we'll iterate on it after.
Ping @michelolzam

**Comment by jonashaag** [comment]
I think it's really good!

Would be even better with a link in the README or repo description :-)

**Comment by mpariente** [comment]
Once we are happy with the docs, I'll link to it, thanks!

Le mer. 12 août 2020 à 16:11, Jonas Haag <notifications@github.com> a
écrit :

**Pull request merged**
