### PR TITLE
Add SuDoRM-RF model

### PR DESCRIPTION
**Pull request by jonashaag**
### Changes from original:

- De-duplicated code that's already in Asteroid and code that's duplicated in SuDoRM-RF

### Example training config:

```yaml
# Model config
# SuDoRM-RF 1.0x:
model:
  out_channels: 128
  in_channels: 512
  num_blocks: 16
  upsampling_depth: 4
  enc_kernel_size: 21
  enc_num_basis: 512
  num_sources: 1
# Best model:
#model:
  #out_channels: 512
  #in_channels: 512 (?)
  #num_blocks: 34
  #upsampling_depth: 4
  #enc_kernel_size: 21
  #enc_num_basis: 512 (?)
  #num_sources: 1
# Default improved
#model:
  #out_channels: 256
  #in_channels: 512
  #num_blocks: 16
  #upsampling_depth: 5
  #enc_kernel_size: 21
  #enc_num_basis: 512
  #num_sources: 1
# Training config
training:
  epochs: 200
  batch_size: 4
  num_workers: 4
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.001
# Data config
data:
  train_dir: data/wav8k/min/tr/
  valid_dir: data/wav8k/min/cv/
  task: sep_clean
  sample_rate: 8000
  mode: min
  segment: 3.0
```

### CODE REVIEW

**Comment by jonashaag** [comment]
I let it train with the config given above yesterday for a few hours and it seems training duration to reach X dB SI-SDR is similar to DPRNN[ks=16].

**Comment by mpariente** [comment]
Thanks for the PR Jonas ! 
Good to have some info about the speed of convergence as well 

If I understand well, you changed `GlobLN` only right? 
I thought that you had a re-implementation. 
This is great but I feel like I should ask @etzinis if he is ok that we integrate his code here? 

If he is ok with that, I'll have few comments on docstrings mainly (because this is not the same style as ours) and we'll merge.

**Comment by jonashaag** [comment]
Sorry, no, not a re-implementation. As said I only de-duplicated some code (for example GlobLN seems to be copy-pasted 1:1 from Asteroid to SuDoRM-RF).

**Comment by etzinis** [comment]
Hey guys! I already have an implementation of sudo rm rf using asteroid.

**Comment by etzinis** [comment]
Whatever you want manu

**Comment by jonashaag** [comment]
Oh well then maybe it’s easier to use your implementation :)

**Comment by mpariente** [comment]
Yes @etzinis, I should have asked before ! 
What are the changes compared to this PR? 

Sorry @jonashaag but it makes more sense to have the code directly from the author or the paper, I hope you understand. Let's keep this PR open until @etzinis decides.

**Comment by jonashaag** [comment]
No worries! Sorry for interfering. I did not realize that @etzinis was aware of Asteroid and even a contributor.

**Comment by etzinis** [comment]
I think @jonashaag  did a great job so I think that we could actually merge his architecture. My implementation was adding stuff into other parts of the code as well. But the very important thing that we also need is the data augmentation part. How about putting a PR with my changes and then @jonashaag  can adjust these changes accordingly to this PR which is in better shape. @mpariente WDYT?

**Comment by mpariente** [comment]
That sounds good ! 
We're waiting for your PR @etzinis then, thanks to both of you

**Comment by etzinis** [comment]
Ok please check this PR https://github.com/mpariente/asteroid/pull/185

**Comment by mpariente** [comment]
So @etzinis, let's merge this?

**Comment by mpariente** [comment]
Integrated asteroid filterbanks, updated docs and included tests. 
@etzinis can you have a look? 
@jonashaag as well maybe?

**Comment by etzinis** [comment]
looks good to me! How about the onliine mixing code?

**Comment by mpariente** [comment]
Thanks for the feedback ! 

> How about the onliine mixing code?

I was thinking of writing a `collate_fn` for it, I'll have a look tonight

**Comment by mpariente** [comment]
```python
        # Augment the data.
        if train:
            # Online mixing over samples of the batch. (This might cause to get
            # utterances from the same speaker but it's highly improbable).
            energies = torch.sum(targets ** 2, dim=-1, keepdim=True)
            new_s1 = targets[torch.randperm(energies.shape[0]), 0, :]
            new_s2 = targets[torch.randperm(energies.shape[0]), 1, :]

            # Why is those lines needed? It's to keep the SNRs of each mixture unchanged? 
            new_s2 = new_s2 * torch.sqrt(energies[:, 1] /
                                         (new_s2 ** 2).sum(-1, keepdims=True))
            new_s1 = new_s1 * torch.sqrt(energies[:, 0] /
                                         (new_s1 ** 2).sum(-1, keepdims=True))
            inputs = new_s1 + new_s2
            targets[:, 0, :] = new_s1
            targets[:, 1, :] = new_s2
```

**Comment by mpariente** [comment]
I added it now. 
We'll merge this for now and see about adding the recipe afterwards (maybe after refactor will be much easier).

**Pull request merged**
