### PR TITLE
Add conda environment

### PR DESCRIPTION
**Pull request by mcernak**

### CODE REVIEW

**Comment by mpariente** [comment]
Ok, I didn't realize that this is what you meant. 
This seems to complicate the instructions without any benefit. Any user can create an empty env, we don't need a empty env file for that right?

**Comment by mcernak** [comment]
My original idea was to use the complete environment as I uploaded in #332. 

But then you asked to use `requirements.txt` for pip install, which is not possible within `environment.yml.`

A solution would be to create an empty conda env, activate it, and install whatever is needed, which updates the environment.

Alternatively, I can prepare the full conda env as I thought.

**Comment by mpariente** [comment]
You can have `-r requirements.txt` in the pip subsection of conda.  

Have a look [here](https://github.com/conda/conda/blob/54e4a91d0da4d659a67e3097040764d3a2f6aa16/tests/conda_env/support/advanced-pip/environment.yml)

We can have 
```yaml
name: asteroid
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - Cython
  -pip
  -pip:
    - -r file:requirements.txt
    - -e .
```
and at least everything is installed in one go.

**Comment by mcernak** [comment]
Correct, I updated the environment.

**Pull request merged**
