### PR TITLE
[black] Update black to 20.8b1

### PR DESCRIPTION
**Pull request by jonashaag**
Part 1 of #224

### CODE REVIEW

**Comment by mpariente** [comment]
Looks like I tend to add a leading space where I shouldn't :joy: 
Thanks !

**Comment by jonashaag** [comment]
Note you can also add `?w=1` to the GH URL to hide whitespace changes.

**Comment by mpariente** [comment]
That's super cool ! 
Where can I find more like this?

**Comment by jonashaag** [comment]
> Where can I find more like this?

I don't know, honestly. You may find the list of keyboard shortcuts helpful; press `?` on this page.

**Pull request merged**
