### PR TITLE
Dynamic Mixing fix 

### PR DESCRIPTION
**Pull request by popcornell**
as noted by JusperLee in mpariente/asteroid#168. 
Added also checks to prevent clipping.

### CODE REVIEW

**Comment by mpariente** [comment]
Also thanks to @JusperLee !

**Comment by JusperLee** [comment]
Thank you very much for your dynamic mixing @popcornell and speech separation library @mpariente .

**Comment by popcornell** [comment]
Yeah it is very weird. It has been merged to master no ?

**Comment by JusperLee** [comment]
yes, it has been merged to master.

**Comment by mpariente** [comment]
> Yeah it is very weird. It has been merged to master no ?

I guess you made a new branch from your last state, which was not master, so it contained the three commits you made in the previous branch. As we squash commits to merge into master, the git trees looked different so it rendered the diff. 
It's just a matter of branch starting point, no problem.

**Pull request merged**
