### PR TITLE
[CI] Build with torch-nightly 

### PR DESCRIPTION
**Pull request by mpariente**
Ugly, but simple (if it works).

I'd be ok with that for now.

### CODE REVIEW

**Comment by jonashaag** [comment]
Yes looks ok. Shall we also test with 1.6?

**Comment by mpariente** [comment]
Yes, let's do that as well

**Comment by jonashaag** [comment]
Very nice!

**Comment by mpariente** [comment]
Don't know.. 
It's not the first time it happens.

**Comment by mpariente** [comment]
Approved solution: https://github.community/t/manually-restart-actions-and-entire-workflows/16262/2

:joy: :joy: :joy:

**Comment by jonashaag** [comment]
I've been told it only works with that exact commit message

**Comment by mpariente** [comment]
I'm wondering if it's necessary to run the tests 6 times

**Pull request merged**
