### PR TITLE
[tests] Add precommit hook with black

### PR DESCRIPTION
**Pull request by mpariente**
First steps towards adopting [`black`](https://github.com/psf/black) !

The idea is to gain time and energy :
- No need to think about code style when writing
- No need to worry about code style when reviewing (huge loss of time)
- Easier for new comers to open their PRs 

For now, we'll stick with 120 line length, but we'll probably move to 100 afterwards. 
Also need to add `flake8` but I don't know it much yet.

**Resources**
- [Django adopting black](https://github.com/django/deps/blob/master/accepted/0008-black.rst): see the end for the procedure we'll follow
- [Why prettier in JS](https://prettier.io/docs/en/why-prettier.html): good read.
- [Linus about line length](https://lkml.org/lkml/2020/5/29/1038).

### CODE REVIEW

**Comment by jonashaag** [comment]
Nice!

Why no string normalization?

**Comment by mpariente** [comment]
It'll probably come when we apply black to the whole codebase. 
For now, two many quotes are single (and I like them better but I should adhere to black..) to enforce double quote now.

**Comment by jonashaag** [comment]
In my opinion changing some style settings of a standardized formatted defeats the purpose (of not having to make any choices). Unless there is no technical reason to not go with the default settings I personally would simply go with the default settings.

**Comment by mpariente** [comment]
I add string normalization in the next PR that does the black formatting. 
However, I think I'll keep line length to 100 instead of 88. I don't see the point of 88 now that Github shows up to 120 chars without scrolling.

**Comment by jonashaag** [comment]
Agreed!

**Pull request merged**
